"""PDF report generator — Sprint 4.

Generates a journal-style multi-section PDF report from a completed
shielding calculation, using ReportLab.

Public API
----------
build_pdf(calc_state, figures, output_path) -> Path
    Build full PDF report and write to *output_path*.  Returns the path.

pdf_bytes(calc_state, figures) -> bytes
    Same but returns raw PDF bytes (for st.download_button).
"""
from __future__ import annotations

import io
import datetime
import logging
from pathlib import Path
from typing import Any

import numpy as np

_log = logging.getLogger(__name__)

# ── ReportLab imports ─────────────────────────────────────────────────────────
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT, TA_JUSTIFY
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm, mm
from reportlab.platypus import (
    BaseDocTemplate,
    Frame,
    PageTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    Image,
    HRFlowable,
    KeepTogether,
    PageBreak,
)
from reportlab.platypus.flowables import HRFlowable

# ── Page geometry ─────────────────────────────────────────────────────────────
_W, _H = A4
_MARGIN = 2.0 * cm
_TEXT_W = _W - 2 * _MARGIN

# ── Colour palette ────────────────────────────────────────────────────────────
_BLUE   = colors.HexColor("#1E3A5F")   # header / title
_LBLUE  = colors.HexColor("#4472C4")   # section rule
_GOLD   = colors.HexColor("#C9A84C")   # accent
_LGRAY  = colors.HexColor("#F5F5F5")   # table stripe
_DGRAY  = colors.HexColor("#555555")   # body text
_BLACK  = colors.black
_WHITE  = colors.white


# ═════════════════════════════════════════════════════════════════════════════
# ── Style sheet ──────────────────────────────────────────────────────────────
# ═════════════════════════════════════════════════════════════════════════════

def _make_styles() -> dict[str, ParagraphStyle]:
    base = getSampleStyleSheet()
    styles: dict[str, ParagraphStyle] = {}

    styles["Title"] = ParagraphStyle(
        "Title",
        parent=base["Title"],
        fontSize=20, textColor=_BLUE,
        spaceAfter=4, spaceBefore=0,
        alignment=TA_CENTER, fontName="Helvetica-Bold",
    )
    styles["Subtitle"] = ParagraphStyle(
        "Subtitle",
        fontSize=11, textColor=_DGRAY,
        alignment=TA_CENTER, fontName="Helvetica",
        spaceAfter=2,
    )
    styles["Meta"] = ParagraphStyle(
        "Meta",
        fontSize=8, textColor=_DGRAY,
        alignment=TA_CENTER, fontName="Helvetica",
        spaceAfter=6,
    )
    styles["H1"] = ParagraphStyle(
        "H1",
        fontSize=13, textColor=_BLUE,
        spaceBefore=14, spaceAfter=4,
        fontName="Helvetica-Bold",
    )
    styles["H2"] = ParagraphStyle(
        "H2",
        fontSize=10, textColor=_LBLUE,
        spaceBefore=8, spaceAfter=3,
        fontName="Helvetica-Bold",
    )
    styles["Body"] = ParagraphStyle(
        "Body",
        fontSize=9, textColor=_DGRAY,
        fontName="Helvetica",
        leading=13, spaceAfter=4,
        alignment=TA_JUSTIFY,
    )
    styles["Caption"] = ParagraphStyle(
        "Caption",
        fontSize=7.5, textColor=_DGRAY,
        fontName="Helvetica-Oblique",
        leading=11, spaceAfter=6,
        alignment=TA_CENTER,
    )
    styles["TableHeader"] = ParagraphStyle(
        "TableHeader",
        fontSize=8, textColor=_WHITE,
        fontName="Helvetica-Bold",
        alignment=TA_CENTER,
    )
    styles["TableCell"] = ParagraphStyle(
        "TableCell",
        fontSize=8, textColor=_DGRAY,
        fontName="Helvetica",
        alignment=TA_CENTER,
    )
    styles["Footer"] = ParagraphStyle(
        "Footer",
        fontSize=7, textColor=_DGRAY,
        fontName="Helvetica",
        alignment=TA_CENTER,
    )
    return styles


# ═════════════════════════════════════════════════════════════════════════════
# ── Page template ────────────────────────────────────────────────────────────
# ═════════════════════════════════════════════════════════════════════════════

def _header_footer(canvas, doc, title: str, version: str):
    """Draw page header rule and footer on each page."""
    canvas.saveState()
    # Header rule
    canvas.setStrokeColor(_LBLUE)
    canvas.setLineWidth(1.2)
    canvas.line(_MARGIN, _H - _MARGIN + 4 * mm, _W - _MARGIN, _H - _MARGIN + 4 * mm)
    # Footer
    canvas.setFont("Helvetica", 7)
    canvas.setFillColor(_DGRAY)
    canvas.drawString(_MARGIN, 12 * mm, f"{title}  ·  Generated by ShieldLab G4 {version}")
    canvas.drawRightString(_W - _MARGIN, 12 * mm,
                           f"Page {doc.page}  ·  {datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}")
    canvas.restoreState()


# ═════════════════════════════════════════════════════════════════════════════
# ── Helper: matplotlib figure → ReportLab Image ──────────────────────────────
# ═════════════════════════════════════════════════════════════════════════════

def _fig_to_rl_image(fig, width_cm: float = 14.5, dpi: int = 200) -> Image:
    """Render a matplotlib Figure into a ReportLab Image flowable."""
    buf = io.BytesIO()
    fig.savefig(buf, format="png", dpi=dpi, bbox_inches="tight",
                facecolor=fig.get_facecolor())
    buf.seek(0)
    img_w = width_cm * cm
    # Preserve aspect ratio
    import matplotlib
    fig_w_in, fig_h_in = fig.get_size_inches()
    aspect = fig_h_in / fig_w_in
    img_h = img_w * aspect
    return Image(buf, width=img_w, height=img_h)


# ═════════════════════════════════════════════════════════════════════════════
# ── Helper: pandas DataFrame → ReportLab Table ───────────────────────────────
# ═════════════════════════════════════════════════════════════════════════════

def _df_to_rl_table(df, styles_map: dict, max_rows: int = 40) -> Table:
    """Convert a pandas DataFrame to a styled ReportLab Table."""
    if len(df) > max_rows:
        df = df.head(max_rows)

    header = [Paragraph(str(c), styles_map["TableHeader"]) for c in df.columns]
    data = [header]
    for _, row in df.iterrows():
        data.append([
            Paragraph(str(v), styles_map["TableCell"]) for v in row
        ])

    col_w = _TEXT_W / len(df.columns)
    t = Table(data, colWidths=[col_w] * len(df.columns), repeatRows=1)

    row_styles = [
        ("BACKGROUND", (0, 0), (-1, 0), _BLUE),
        ("TEXTCOLOR",  (0, 0), (-1, 0), _WHITE),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [_WHITE, _LGRAY]),
        ("GRID",       (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
        ("VALIGN",     (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("LEFTPADDING",  (0, 0), (-1, -1), 5),
        ("RIGHTPADDING", (0, 0), (-1, -1), 5),
    ]
    t.setStyle(TableStyle(row_styles))
    return t


# ═════════════════════════════════════════════════════════════════════════════
# ── Main builder ─────────────────────────────────────────────────────────────
# ═════════════════════════════════════════════════════════════════════════════

def pdf_bytes(
    calc_state: dict[str, Any],
    figures: dict[str, Any],   # name → matplotlib Figure  (may be empty)
    version: str = "0.1.0",
) -> bytes:
    """Build a PDF report and return raw bytes.

    Parameters
    ----------
    calc_state : dict
        The ``st.session_state['calc_state']`` dict from the shielding
        calculator (keys: mat_name, density, mass_fractions, energies_MeV,
        thicknesses_cm, particle, energy_display, …).
    figures : dict
        Mapping of label → matplotlib Figure objects to embed.
        Pass ``{}`` if no figures are available.
    version : str
        ShieldLab G4 version string for footer / title.
    """
    import pandas as pd
    from shieldlab.physics.shielding_params import (
        compute_shielding_table, compute_fnrcs, compute_fnrcs_hvl, GP_MATERIALS,
    )
    from shieldlab.core.descriptors import material_descriptors

    buf = io.BytesIO()
    S = _make_styles()
    ts = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    name     = calc_state.get("mat_name", "Unknown")
    rho      = calc_state.get("density", 0.0)
    mf       = calc_state.get("mass_fractions", {})
    E_arr    = np.asarray(calc_state.get("energies_MeV", [0.662]))
    T_arr    = np.asarray(calc_state.get("thicknesses_cm", [5.0]))
    particle = calc_state.get("particle", "gamma")
    e_disp   = calc_state.get("energy_display", "")
    gp_mat   = calc_state.get("gp_mat", "Water, Liquid")

    doc_title = f"ShieldLab G4 — Shielding Report: {name}"

    def _on_page(canvas, doc):
        _header_footer(canvas, doc, doc_title, version)

    # ── Build doc ─────────────────────────────────────────────────────────────
    doc = BaseDocTemplate(
        buf, pagesize=A4,
        leftMargin=_MARGIN, rightMargin=_MARGIN,
        topMargin=_MARGIN + 6 * mm, bottomMargin=_MARGIN + 6 * mm,
    )
    frame = Frame(doc.leftMargin, doc.bottomMargin,
                  doc.width, doc.height, id="main")
    template = PageTemplate(id="main", frames=[frame], onPage=_on_page)
    doc.addPageTemplates([template])

    story = []

    # ── Cover ─────────────────────────────────────────────────────────────────
    story.append(Spacer(1, 1.5 * cm))
    story.append(Paragraph("ShieldLab G4", S["Title"]))
    story.append(Paragraph("Radiation Shielding Analysis Report", S["Subtitle"]))
    story.append(HRFlowable(width="100%", thickness=1.5, color=_GOLD, spaceAfter=6))
    story.append(Paragraph(f"Material: <b>{name}</b>", S["Subtitle"]))
    story.append(Paragraph(
        f"ρ = {rho:.4f} g/cm³  ·  Particle: {particle}  ·  {e_disp}", S["Subtitle"]
    ))
    story.append(Paragraph(f"Generated: {ts}  ·  Version: {version}", S["Meta"]))
    story.append(Spacer(1, 0.8 * cm))

    # ── Section 1: Material composition ──────────────────────────────────────
    story.append(Paragraph("1. Material Composition", S["H1"]))
    story.append(HRFlowable(width="100%", thickness=0.6, color=_LBLUE, spaceAfter=4))

    story.append(Paragraph(
        f"Material <b>{name}</b> with bulk density ρ = {rho:.4f} g/cm³. "
        f"Elemental composition (mass fractions):", S["Body"]
    ))

    comp_data = [["Element", "Weight fraction", "Weight %"]]
    for el, wf in sorted(mf.items(), key=lambda x: -x[1]):
        comp_data.append([el, f"{wf:.6f}", f"{wf*100:.3f}%"])
    comp_cols = [3 * cm, 5 * cm, 5 * cm]
    comp_t = Table(comp_data, colWidths=comp_cols, repeatRows=1)
    comp_t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), _BLUE),
        ("TEXTCOLOR",  (0, 0), (-1, 0), _WHITE),
        ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE",   (0, 0), (-1, -1), 8),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [_WHITE, _LGRAY]),
        ("GRID",       (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
        ("ALIGN",      (1, 0), (-1, -1), "CENTER"),
        ("VALIGN",     (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(comp_t)
    story.append(Spacer(1, 4 * mm))

    # Material descriptors
    try:
        desc = material_descriptors(name, mf, rho)
        desc_rows = [
            ["Density (g/cm³)",           f"{rho:.4f}"],
            ["Molar mass (g/mol)",         f"{desc['molar_mass_g_mol']:.4f}"],
            ["Mean Z",                     f"{desc['average_Z']:.4f}"],
            ["Zeff (n=3.5, static)",       f"{desc['Zeff_3p5']:.4f}"],
            ["Neff (el/cm³)",              f"{desc['Neff_electrons_cm3']:.4e}"],
            ["Electron density (el/cm³)",  f"{desc['electron_density_cm3']:.4e}"],
        ]
        desc_t = Table([["Parameter", "Value"]] + desc_rows,
                       colWidths=[8 * cm, 6 * cm], repeatRows=1)
        desc_t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), _BLUE),
            ("TEXTCOLOR",  (0, 0), (-1, 0), _WHITE),
            ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",   (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [_WHITE, _LGRAY]),
            ("GRID",       (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
            ("VALIGN",     (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        story.append(desc_t)
    except Exception:
        _log.warning(
            "Could not build material descriptor table for PDF report \u2014 section will be skipped",
            exc_info=True,
        )

    story.append(Spacer(1, 6 * mm))

    # ── Section 2: Photon shielding parameters ────────────────────────────────
    story.append(Paragraph("2. Photon Shielding Parameters (Phy-X / NIST XCOM)", S["H1"]))
    story.append(HRFlowable(width="100%", thickness=0.6, color=_LBLUE, spaceAfter=4))
    story.append(Paragraph(
        "Mass attenuation coefficient μ/ρ and derived parameters computed from NIST "
        "XrayMassCoef database by mixture rule. Buildup factors via G-P method "
        f"(reference material: {gp_mat}). HVL = ln(2)/μ, TVL = ln(10)/μ, MFP = 1/μ.",
        S["Body"]
    ))

    try:
        df_sh = compute_shielding_table(mf, rho, E_arr, T_arr, gp_material=gp_mat)
        sh_cols = ["Energy_keV", "μ/ρ (cm²/g)", "μen/ρ (cm²/g)", "μ (cm⁻¹)",
                   "HVL (cm)", "TVL (cm)", "MFP (cm)"]
        sh_cols = [c for c in sh_cols if c in df_sh.columns]
        df_show = df_sh[sh_cols].round(5)
        # Limit rows for readability
        if len(df_show) > 30:
            step = max(1, len(df_show) // 30)
            df_show = df_show.iloc[::step].copy()
        story.append(_df_to_rl_table(df_show, S, max_rows=35))

        # Inline summary at reference energies
        story.append(Spacer(1, 3 * mm))
        ref_es = [100.0, 662.0, 1250.0]
        E_keV_arr = E_arr * 1000
        for e_ref in ref_es:
            ei = int(np.argmin(np.abs(E_keV_arr - e_ref)))
            if abs(float(E_keV_arr[ei]) - e_ref) < e_ref * 0.5:
                row = df_sh.iloc[ei]
                mac_v  = row.get("μ/ρ (cm²/g)", float("nan"))
                hvl_v  = row.get("HVL (cm)", float("nan"))
                tvl_v  = row.get("TVL (cm)", float("nan"))
                story.append(Paragraph(
                    f"At <b>{float(E_keV_arr[ei]):.1f} keV</b>: "
                    f"μ/ρ = {mac_v:.4f} cm²/g, "
                    f"HVL = {hvl_v:.3f} cm, TVL = {tvl_v:.3f} cm.",
                    S["Body"]
                ))
    except Exception as exc:
        story.append(Paragraph(f"(Table generation failed: {exc})", S["Body"]))

    # ── Section 3: Neutron shielding ──────────────────────────────────────────
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph("3. Fast Neutron Removal (FNRCS / NGCal)", S["H1"]))
    story.append(HRFlowable(width="100%", thickness=0.6, color=_LBLUE, spaceAfter=4))

    try:
        from shieldlab.physics.shielding_params import FNRCS_BARNS
        from shieldlab.physics.nist_xcom import ATOMIC_MASS
        sigma_R = compute_fnrcs(mf, rho)
        hvl_n, tvl_n = compute_fnrcs_hvl(sigma_R)
        mfp_n = 1.0 / sigma_R if sigma_R > 0 else float("inf")
        story.append(Paragraph(
            f"Fast neutron removal cross section Σ_R = <b>{sigma_R:.4f} cm⁻¹</b>  ·  "
            f"HVL_n = <b>{hvl_n:.3f} cm</b>  ·  TVL_n = <b>{tvl_n:.3f} cm</b>  ·  "
            f"MFP_n = <b>{mfp_n:.3f} cm</b>",
            S["Body"]
        ))
        NA = 6.02214076e23
        fn_rows = [["Element", "wt frac", "σ_R (barn)", "A (g/mol)", "Σ_Rᵢ (cm⁻¹)"]]
        for sym, wf in sorted(mf.items(), key=lambda x: -x[1]):
            sb = FNRCS_BARNS.get(sym)
            A  = ATOMIC_MASS.get(sym)
            if sb and A:
                contrib = wf * (NA / A) * sb * 1e-24 * rho
                fn_rows.append([sym, f"{wf:.4f}", f"{sb:.3f}", f"{A:.3f}", f"{contrib:.5f}"])
        fn_t = Table(fn_rows,
                     colWidths=[2.5*cm, 3*cm, 3*cm, 3*cm, 3.5*cm],
                     repeatRows=1)
        fn_t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), _BLUE),
            ("TEXTCOLOR",  (0, 0), (-1, 0), _WHITE),
            ("FONTNAME",   (0, 0), (-1, 0), "Helvetica-Bold"),
            ("FONTSIZE",   (0, 0), (-1, -1), 8),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [_WHITE, _LGRAY]),
            ("GRID",       (0, 0), (-1, -1), 0.4, colors.HexColor("#CCCCCC")),
            ("ALIGN",      (1, 0), (-1, -1), "CENTER"),
            ("VALIGN",     (0, 0), (-1, -1), "MIDDLE"),
            ("TOPPADDING", (0, 0), (-1, -1), 3),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ]))
        story.append(fn_t)
    except Exception as exc:
        story.append(Paragraph(f"(FNRCS computation failed: {exc})", S["Body"]))

    # ── Section 4: Embedded figures ───────────────────────────────────────────
    if figures:
        story.append(PageBreak())
        story.append(Paragraph("4. Figures", S["H1"]))
        story.append(HRFlowable(width="100%", thickness=0.6, color=_LBLUE, spaceAfter=4))

        fig_num = 1
        for fig_label, fig_obj in figures.items():
            if fig_obj is None:
                continue
            try:
                img = _fig_to_rl_image(fig_obj, width_cm=14.5, dpi=200)
                story.append(KeepTogether([
                    img,
                    Paragraph(
                        f"<b>Figure {fig_num}.</b> {fig_label}",
                        S["Caption"]
                    ),
                    Spacer(1, 4 * mm),
                ]))
                fig_num += 1
            except Exception as exc:
                story.append(Paragraph(f"(Figure '{fig_label}' failed: {exc})", S["Body"]))

    # ── Section 5: Methods & references ──────────────────────────────────────
    story.append(Spacer(1, 6 * mm))
    story.append(Paragraph("5. Methods &amp; Data Sources", S["H1"]))
    story.append(HRFlowable(width="100%", thickness=0.6, color=_LBLUE, spaceAfter=4))
    story.append(Paragraph(
        "Mass attenuation and energy-absorption coefficients: NIST XrayMassCoef database "
        "(Hubbell &amp; Seltzer, 2004). Buildup factors: G-P fitting method per "
        "ANSI/ANS-6.4.3-1991. Fast neutron removal cross sections: tabulated σ_R values "
        "from Shultis &amp; Faw, <i>Radiation Shielding</i> (2000). Electron stopping "
        "powers: Bethe–Bloch formula per ICRU Report 37. Ion stopping: ICRU Report 49 + "
        "ZBL nuclear stopping.",
        S["Body"]
    ))
    story.append(Paragraph(
        f"Report generated by <b>ShieldLab G4 v{version}</b> — "
        "an open-source radiation shielding analytics platform.",
        S["Body"]
    ))

    # ── Build ─────────────────────────────────────────────────────────────────
    doc.build(story)
    return buf.getvalue()
